require("iman.plugins-setup")
require("iman.core.options")
require("iman.core.keymaps")
require("iman.core.colorscheme")
require("iman.plugins.comment")
require("iman.plugins.nvim-tree")
require("iman.plugins.lualine")
require("iman.plugins.telescope")
require("iman.plugins.nvim-cmp")
require("iman.plugins.lsp.mason")
require("iman.plugins.lsp.lspsaga")
require("iman.plugins.lsp.lspconfig")
require("iman.plugins.lsp.null-ls")
require("iman.plugins.autopairs")
require("iman.plugins.treesitter")
require("iman.plugins.gitsigns")
require("iman.plugins.whichkey")
require("iman.plugins.toggleterm")
require("iman.plugins.bufferline")

vim.o.foldenable = false
